### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mammadataei** [mammadataei/dom-assertions#16]
These are the tasks that need to get done:

## dom-assertions

- [ ] extract all assertions from `jest-dom`.
- [ ] document the assertions interface and usage guides for developing custom assertions.

## jest-dom

- [ ] refactor all assertions and error messages using the `dom-assertions` package
- [ ] migrate the codebase to typescript
- [ ] update the build process to emit `ESM` output
- [ ] clean up the dependencies and configurations to use the ones shared across monorepo

## chai-dom

- [ ] add more assertions
- [ ] update the documentation details

## cypress-dom

- [ ] add more assertions
- [ ] update the documentation details

## general

- [ ] update the release process since the old configurations are not working in a monorepo
- [ ] update the contribution guidelines
- [ ] update issue/pr templates

**Comment by yannbf** [comment]
Hey @mammadataei thanks a lot for creating this roadmap! Do you have any idea how feasible this is for this year? Is there something the community can help?

**Comment by mammadataei** [comment]
Hi @yannbf, I'm trying to put more time into this and I hope it will finish by the end of the second quarter of this year. Clearly, it can progress faster with some help. The primary task is to extract all assertions from the `jest-dom` package to `dom-assertions` and stabilize the rest by improving the test coverage.
